import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, unlinkSync } from 'fs'
import { join } from 'path'
import { createHash } from 'crypto'
import { dataDir } from '../store'
import type { MemoryNote } from '@common/types'
import type { ChatProvider } from '../providers/types'

// Aura's memory is an Obsidian-style wiki vault: one markdown note per
// memory with YAML frontmatter and [[wikilinks]] between related notes,
// plus an auto-generated MEMORY.md index. The whole folder is plain
// markdown — open it in Obsidian, edit it by hand, sync it, grep it.
//
// Recall ranking (ported from the original Jarvis memory system):
//   score = 0.7·similarity + 0.2·(importance/5) + 0.1·exp(-ageDays/30)
// Similarity uses embeddings when the provider offers them (cached in a
// sidecar file so the markdown stays pure), else keyword overlap.

export function defaultVaultPath(): string {
  return join(dataDir(), 'memory-vault')
}

export function personaVaultPath(personaId: string, basePath = defaultVaultPath()): string {
  const safe = sanitizeSlug(personaId) || 'unknown'
  return join(basePath, 'characters', safe)
}

export class MemoryVault {
  constructor(private vaultPath: string) {
    if (!existsSync(this.vaultPath)) mkdirSync(this.vaultPath, { recursive: true })
  }

  get path(): string {
    return this.vaultPath
  }

  // ---------- markdown <-> note ----------

  private noteFile(slug: string): string {
    return join(this.vaultPath, `${slug}.md`)
  }

  private serialize(note: MemoryNote): string {
    const fm = [
      '---',
      `title: ${note.title.replace(/\n/g, ' ')}`,
      `type: ${note.type}`,
      `importance: ${note.importance}`,
      `created: ${note.createdAt}`,
      `updated: ${note.updatedAt}`,
      note.source ? `source: ${note.source}` : null,
      '---'
    ].filter(Boolean)
    return `${fm.join('\n')}\n\n${note.body.trim()}\n`
  }

  private parse(slug: string, raw: string): MemoryNote | null {
    const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/)
    const meta: Record<string, string> = {}
    let body = raw
    if (match) {
      body = match[2]
      for (const line of match[1].split(/\r?\n/)) {
        const idx = line.indexOf(':')
        if (idx > 0) meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim()
      }
    }
    const now = new Date().toISOString()
    return {
      slug,
      title: meta.title || slug.replace(/-/g, ' '),
      type: meta.type || 'fact',
      importance: clampImportance(parseInt(meta.importance ?? '3', 10)),
      body: body.trim(),
      createdAt: meta.created || now,
      updatedAt: meta.updated || now,
      source: meta.source || undefined
    }
  }

  // ---------- CRUD ----------

  list(): MemoryNote[] {
    if (!existsSync(this.vaultPath)) return []
    const notes: MemoryNote[] = []
    for (const file of readdirSync(this.vaultPath)) {
      if (!file.endsWith('.md') || file === 'MEMORY.md') continue
      try {
        const note = this.parse(file.slice(0, -3), readFileSync(this.noteFile(file.slice(0, -3)), 'utf8'))
        if (note && note.body) notes.push(note)
      } catch { /* skip unreadable note */ }
    }
    return notes.sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1))
  }

  get(slug: string): MemoryNote | null {
    const safe = sanitizeSlug(slug)
    if (!safe) return null
    const file = this.noteFile(safe)
    if (!existsSync(file)) return null
    return this.parse(safe, readFileSync(file, 'utf8'))
  }

  save(note: MemoryNote): void {
    // Preserve existing slugs verbatim (hand-edited vault files may use any
    // filename); only generate a slug for brand-new notes.
    note.slug = sanitizeSlug(note.slug) || slugify(note.title)
    note.updatedAt = new Date().toISOString()
    if (!note.createdAt) note.createdAt = note.updatedAt
    writeFileSync(this.noteFile(note.slug), this.serialize(note), 'utf8')
    this.writeIndex()
  }

  delete(slug: string): void {
    const safe = sanitizeSlug(slug)
    if (!safe) return
    try {
      const file = this.noteFile(safe)
      if (existsSync(file)) unlinkSync(file)
    } catch { /* ignore */ }
    this.dropEmbedding(safe)
    this.writeIndex()
  }

  private writeIndex(): void {
    const notes = this.list()
    const lines = [
      '# Memory Index',
      '',
      `_${notes.length} memories. Auto-generated by Aura — edit the individual notes, not this file._`,
      ''
    ]
    const byType = new Map<string, MemoryNote[]>()
    for (const n of notes) {
      const list = byType.get(n.type) ?? []
      list.push(n)
      byType.set(n.type, list)
    }
    for (const [type, group] of [...byType.entries()].sort()) {
      lines.push(`## ${type}`, '')
      for (const n of group) lines.push(`- [[${n.slug}]] — ${n.title}`)
      lines.push('')
    }
    writeFileSync(join(this.vaultPath, 'MEMORY.md'), lines.join('\n'), 'utf8')
  }

  // ---------- embeddings sidecar ----------
  // Vectors are only comparable within one embedding space, so the sidecar
  // records which model produced them and is wiped when the model changes.

  private embeddingsFile(): string {
    const dir = join(this.vaultPath, '.aura')
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    return join(dir, 'embeddings.json')
  }

  private loadEmbeddings(modelId: string): EmbeddingSidecar {
    try {
      const raw = JSON.parse(readFileSync(this.embeddingsFile(), 'utf8')) as EmbeddingSidecar
      if (raw.model !== modelId || typeof raw.entries !== 'object') {
        return { model: modelId, entries: {} }
      }
      return raw
    } catch {
      return { model: modelId, entries: {} }
    }
  }

  private saveEmbeddings(sidecar: EmbeddingSidecar): void {
    writeFileSync(this.embeddingsFile(), JSON.stringify(sidecar), 'utf8')
  }

  private dropEmbedding(slug: string): void {
    try {
      const raw = JSON.parse(readFileSync(this.embeddingsFile(), 'utf8')) as EmbeddingSidecar
      if (raw.entries?.[slug]) {
        delete raw.entries[slug]
        this.saveEmbeddings(raw)
      }
    } catch { /* no sidecar yet */ }
  }

  /** Ensure every note has an up-to-date embedding; quietly no-ops when the provider can't embed. */
  async ensureEmbeddings(provider: ChatProvider): Promise<void> {
    if (!provider.embed || !provider.embeddingId) return
    const sidecar = this.loadEmbeddings(provider.embeddingId)
    let dirty = false
    for (const note of this.list()) {
      const text = `${note.title}\n${note.body}`
      const hash = sha1(text)
      if (sidecar.entries[note.slug]?.hash === hash) continue
      const vector = await provider.embed(text).catch(() => null)
      if (!vector) break // embeddings unavailable; keyword recall will cover it
      sidecar.entries[note.slug] = { hash, vector }
      dirty = true
    }
    if (dirty) this.saveEmbeddings(sidecar)
  }

  // ---------- recall ----------

  async recall(query: string, k: number, provider?: ChatProvider): Promise<MemoryNote[]> {
    const notes = this.list()
    if (notes.length === 0) return []

    let queryVec: number[] | null = null
    let entries: EmbeddingSidecar['entries'] = {}
    if (provider?.embed && provider.embeddingId) {
      await this.ensureEmbeddings(provider)
      entries = this.loadEmbeddings(provider.embeddingId).entries
      queryVec = await provider.embed(query).catch(() => null)
    }

    const now = Date.now()
    const scored = notes.map(note => {
      const vec = queryVec ? entries[note.slug]?.vector : undefined
      const usable = vec !== undefined && queryVec !== null && vec.length === queryVec.length
      const sim = usable
        ? cosine(queryVec!, vec!)
        : keywordSimilarity(query, `${note.title} ${note.type} ${note.body}`)
      // Different similarity spaces need different relevance gates.
      const threshold = usable ? 0.3 : 0.08
      const ageDays = Math.max(0, (now - Date.parse(note.updatedAt)) / 86_400_000)
      const score = 0.7 * sim + 0.2 * (note.importance / 5) + 0.1 * Math.exp(-ageDays / 30)
      return { note, sim, threshold, score }
    })

    return scored
      .filter(s => s.sim > s.threshold)
      .sort((a, b) => b.score - a.score)
      .slice(0, k)
      .map(s => s.note)
  }
}

interface EmbeddingSidecar {
  model: string
  entries: Record<string, { hash: string; vector: number[] }>
}

// ---------- helpers ----------

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 60) || `note-${Date.now()}`
}

/** Keep an existing slug/filename as-is, stripping only path-dangerous parts. */
export function sanitizeSlug(slug: string): string {
  return (slug ?? '')
    .replace(/[/\\]/g, '')
    .replace(/\.\./g, '')
    .replace(/[\0<>:"|?*]/g, '')
    .trim()
    .slice(0, 120)
}

export function clampImportance(n: number): number {
  return Number.isFinite(n) ? Math.min(5, Math.max(1, Math.round(n))) : 3
}

function sha1(text: string): string {
  return createHash('sha1').update(text).digest('hex')
}

function cosine(a: number[], b: number[]): number {
  if (a.length !== b.length || a.length === 0) return 0
  let dot = 0
  let na = 0
  let nb = 0
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i]
    na += a[i] * a[i]
    nb += b[i] * b[i]
  }
  const denom = Math.sqrt(na) * Math.sqrt(nb)
  return denom === 0 ? 0 : dot / denom
}

const STOPWORDS = new Set(['the', 'and', 'for', 'that', 'this', 'with', 'you', 'your', 'about', 'what', 'have', 'from', 'they', 'their', 'them', 'was', 'are', 'were', 'been', 'being', 'has', 'had', 'can', 'could', 'would', 'should', 'will', 'just', 'like', 'know', 'want', 'tell', 'did', 'does', 'not', 'but', 'get', 'got', 'how', 'why', 'when', 'where', 'who'])

function terms(text: string): Set<string> {
  return new Set(
    text
      .toLowerCase()
      .split(/[^a-z0-9가-힣]+/)
      .filter(t => t.length > 2 && !STOPWORDS.has(t))
  )
}

function keywordSimilarity(query: string, doc: string): number {
  const q = terms(query)
  if (q.size === 0) return 0
  const d = terms(doc)
  let hits = 0
  for (const t of q) if (d.has(t)) hits++
  return hits / q.size
}
